In [5]:
import torch

In [6]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [8]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [16]:
##Calculating the output of this network using the weights and bias tensors
weights = weights.reshape(5,1)
output = activation(torch.sum(weights*features) + bias)
output

tensor([[0.0448]])

In [18]:
## Calculating the output of this network using matrix multiplication
output = activation(torch.mm(features,weights) + bias)
output

tensor([[0.1595]])

In [19]:
torch.manual_seed(7)
features = torch.randn((1, 3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1
W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [20]:
##Calculating the output for this multi-layer network using the weights W1 & W2, and the biases, B1 & B2.
hidden = activation(torch.mm(features,W1)+B1)
output = activation(torch.mm(hidden,W2)+B2)
output

tensor([[0.3171]])

In [21]:
import numpy as np
a = np .random.rand(4,3)
a

array([[0.2864688 , 0.791478  , 0.55696131],
       [0.46893787, 0.75767072, 0.69386983],
       [0.39022399, 0.19721408, 0.48015419],
       [0.81481747, 0.68187022, 0.80334286]])

In [22]:
b = torch.from_numpy(a)
b

tensor([[0.2865, 0.7915, 0.5570],
        [0.4689, 0.7577, 0.6939],
        [0.3902, 0.1972, 0.4802],
        [0.8148, 0.6819, 0.8033]], dtype=torch.float64)

In [23]:
b.numpy()

array([[0.2864688 , 0.791478  , 0.55696131],
       [0.46893787, 0.75767072, 0.69386983],
       [0.39022399, 0.19721408, 0.48015419],
       [0.81481747, 0.68187022, 0.80334286]])

In [24]:
b.mul_(2)


tensor([[0.5729, 1.5830, 1.1139],
        [0.9379, 1.5153, 1.3877],
        [0.7804, 0.3944, 0.9603],
        [1.6296, 1.3637, 1.6067]], dtype=torch.float64)

In [25]:
a

array([[0.57293759, 1.582956  , 1.11392262],
       [0.93787574, 1.51534143, 1.38773965],
       [0.78044797, 0.39442817, 0.96030838],
       [1.62963494, 1.36374044, 1.60668573]])