In [42]:
import pandas as pd
import numpy as np

In [43]:
data = pd.read_csv('train.csv')
data = data.drop(columns = "id")


In [44]:
train_set = data.drop('target',axis=1)
train_target = data['target']


In [45]:
mean = train_set.mean(axis=0)
std = train_set.std(axis=0)
train_set = (train_set - mean)/std


In [46]:
trt_df = pd.DataFrame(train_target)
trt_df = pd.get_dummies(train_target, columns = "target",dtype = int)

In [47]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_set, trt_df)

In [48]:
reg.coef_

array([[ 3.95404991e-04,  2.38117444e-04, -3.82726409e-04,
        -2.16621778e-04,  8.07143437e-04,  1.03172716e-03,
         2.63086489e-04,  2.06211747e-04, -4.44870462e-04,
         6.76626502e-05, -1.14278181e-03,  1.08601121e-03,
        -1.10794806e-03,  2.66767281e-04, -6.44898409e-04,
         8.73291764e-04, -9.44393297e-04, -2.31074551e-04,
        -2.05815410e-03,  5.89203532e-04,  1.39563213e-03,
        -8.54813740e-04,  2.33068490e-04, -1.20959067e-03,
         2.26821040e-04,  9.29982332e-04,  3.30953417e-04,
         5.52092391e-04,  2.90241864e-04,  7.29121418e-04,
         6.02386358e-05, -1.96041337e-04,  4.65334400e-04,
         8.93508055e-04,  1.29788484e-04,  6.50575239e-05,
         1.42262759e-05, -1.07171968e-03,  2.83401123e-04,
         1.50022290e-03, -2.09867979e-04,  9.89923138e-04,
         6.22580127e-04, -6.72510663e-04, -1.01250942e-03,
        -8.35911224e-04,  1.53000879e-04,  5.12272406e-04,
        -3.01302171e-04, -8.19246519e-04,  9.52516025e-0

In [49]:
reg.intercept_

array([0.04559 , 0.122155, 0.07399 , 0.02352 , 0.01532 , 0.259055,
       0.073845, 0.258815, 0.12771 ])

In [50]:
test_data = pd.read_csv("test.csv")
td_id = test_data['id']
td = test_data.drop('id',axis = 1)
mean = td.mean(axis=0)
std = td.std(axis=0)
td = (td - mean)/std
td


feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0      -0.246461  -0.289939  -0.340901  -0.305382  -0.269553  -0.277977   
1       0.002361   0.206311  -0.340901  -0.305382  -0.269553  -0.277977   
2      -0.246461  -0.041814   0.752367  -0.173538  -0.269553  -0.277977   
3      -0.246461  -0.289939  -0.340901   0.221993   0.751416  -0.084335   
4      -0.246461  -0.289939   0.440005  -0.305382  -0.269553  -0.277977   
...          ...        ...        ...        ...        ...        ...   
99995  -0.246461  -0.289939  -0.340901  -0.305382  -0.269553  -0.277977   
99996  -0.246461  -0.289939  -0.340901  -0.305382  -0.269553  -0.084335   
99997  -0.246461  -0.289939  -0.340901  -0.305382  -0.269553  -0.277977   
99998  -0.246461  -0.289939  -0.340901  -0.305382   0.411093   0.109307   
99999  -0.246461  -0.289939  -0.340901  -0.305382  -0.269553  -0.277977   

       feature_6  feature_7  feature_8  feature_9  ...  feature_65  \
0      -0.257023  -0.300435  -0.493949  -0.292018  ...   -0.354183   
1      -0.257023  -0.300435  -0.493949  -0.292018  ...    0.236913   
2      -0.257023  -0.300435   1.029510  -0.292018  ...    0.236913   
3      -0.257023  -0.300435  -0.493949  -0.292018  ...   -0.354183   
4      -0.257023  -0.300435  -0.493949   1.069293  ...   -0.354183   
...          ...        ...        ...        ...  ...         ...   
99995  -0.257023  -0.300435  -0.493949  -0.292018  ...   -0.354183   
99996  -0.257023  -0.300435  -0.493949  -0.292018  ...   -0.354183   
99997  -0.257023  -0.300435  -0.493949  -0.292018  ...   -0.354183   
99998  -0.257023  -0.300435  -0.240039  -0.292018  ...   -0.157151   
99999   1.259442  -0.300435  -0.240039   1.579785  ...   -0.354183   

       feature_66  feature_67  feature_68  feature_69  feature_70  feature_71  \
0       -0.271905   -0.253651   -0.239527   -0.326833   -0.251128   -0.328936   
1        0.261975    0.170595   -0.239527   -0.326833   -0.251128   -0.328936   
2       -0.271905   -0.253651   -0.239527   -0.326833    0.375913   -0.328936   
3       -0.271905   -0.253651    0.023788   -0.326833   -0.251128   -0.328936   
4       -0.271905   -0.253651   -0.239527   -0.326833   -0.251128   -0.328936   
...           ...         ...         ...         ...         ...         ...   
99995   -0.271905   -0.253651   -0.239527   -0.326833   -0.251128   -0.328936   
99996   -0.271905   -0.253651   -0.239527   -0.326833   -0.251128   -0.328936   
99997   -0.271905   -0.112236   -0.239527   -0.326833   -0.251128   -0.328936   
99998   -0.271905   -0.253651   -0.239527   -0.326833   -0.042114   -0.328936   
99999    0.795855   -0.253651   -0.239527   -0.326833   -0.251128   -0.328936   

       feature_72  feature_73  feature_74  
0       -0.295545   -0.272067   -0.161275  
1        0.379544   -0.272067   -0.161275  
2        0.154514   -0.272067   -0.161275  
3        0.604574   -0.272067   -0.161275  
4       -0.295545   -0.179374   -0.161275  
...           ...         ...         ...  
99995   -0.295545   -0.272067   -0.161275  
99996   -0.295545   -0.272067   -0.161275  
99997   -0.295545   -0.272067    0.341069  
99998   -0.070515   -0.272067   -0.161275  
99999   -0.295545   -0.272067   -0.161275  

[100000 rows x 75 columns]

In [51]:
td_np = td.to_numpy()
td_np


array([[-0.2464611 , -0.28993852, -0.3409015 , ..., -0.29554493,
        -0.27206713, -0.16127484],
       [ 0.00236132,  0.20631062, -0.3409015 , ...,  0.37954399,
        -0.27206713, -0.16127484],
       [-0.2464611 , -0.04181395,  0.75236724, ...,  0.15451435,
        -0.27206713, -0.16127484],
       ...,
       [-0.2464611 , -0.28993852, -0.3409015 , ..., -0.29554493,
        -0.27206713,  0.34106858],
       [-0.2464611 , -0.28993852, -0.3409015 , ..., -0.07051529,
        -0.27206713, -0.16127484],
       [-0.2464611 , -0.28993852, -0.3409015 , ..., -0.29554493,
        -0.27206713, -0.16127484]])

In [52]:
pred = reg.predict(td)
pred

array([[0.04658851, 0.20433653, 0.10707238, ..., 0.05219408, 0.16922697,
        0.13687907],
       [0.04490282, 0.16092062, 0.08926591, ..., 0.06398546, 0.21957824,
        0.13271764],
       [0.04383278, 0.13299774, 0.07521787, ..., 0.05851946, 0.20485741,
        0.12108112],
       ...,
       [0.04756381, 0.19935091, 0.10583959, ..., 0.05319285, 0.18135912,
        0.13663341],
       [0.03921375, 0.05695323, 0.04381837, ..., 0.06925935, 0.27783579,
        0.10723882],
       [0.04420212, 0.16342255, 0.09250504, ..., 0.05861234, 0.19402784,
        0.12863081]])

In [53]:
pred_df = pd.DataFrame(pred)
pred_df

0         1         2         3         4         5         6  \
0      0.046589  0.204337  0.107072  0.024318  0.012841  0.246543  0.052194   
1      0.044903  0.160921  0.089266  0.022774  0.013488  0.252367  0.063985   
2      0.043833  0.132998  0.075218  0.021400  0.012868  0.329225  0.058519   
3      0.041443  0.122391  0.076962  0.027549  0.013071  0.253165  0.072961   
4      0.037599  0.105664  0.066724  0.019721  0.013427  0.289462  0.068476   
...         ...       ...       ...       ...       ...       ...       ...   
99995  0.048452  0.203196  0.107745  0.024938  0.013429  0.231478  0.052575   
99996  0.046023  0.188151  0.101938  0.022545  0.013533  0.254456  0.054816   
99997  0.047564  0.199351  0.105840  0.024190  0.013205  0.238666  0.053193   
99998  0.039214  0.056953  0.043818  0.014802  0.011370  0.379508  0.069259   
99999  0.044202  0.163423  0.092505  0.022809  0.014843  0.280947  0.058612   

              7         8  
0      0.169227  0.136879  
1      0.219578  0.132718  
2      0.204857  0.121081  
3      0.261146  0.131314  
4      0.272769  0.126159  
...         ...       ...  
99995  0.180186  0.138001  
99996  0.183331  0.135208  
99997  0.181359  0.136633  
99998  0.277836  0.107239  
99999  0.194028  0.128631  

[100000 rows x 9 columns]

In [54]:
from sklearn import preprocessing

x = pred_df.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
pred_df = pd.DataFrame(x_scaled)
pred_df

0         1         2         3         4         5         6  \
0      0.433285  0.883360  0.811159  0.430421  0.271398  0.451474  0.161206   
1      0.420300  0.828810  0.763612  0.408030  0.281587  0.455837  0.207079   
2      0.412057  0.793726  0.726100  0.388098  0.271827  0.513417  0.185814   
3      0.393646  0.780399  0.730757  0.477275  0.275011  0.456435  0.241996   
4      0.364035  0.759382  0.703418  0.363746  0.280633  0.483628  0.224548   
...         ...       ...       ...       ...       ...       ...       ...   
99995  0.447637  0.881927  0.812955  0.439417  0.280653  0.440188  0.162687   
99996  0.428932  0.863024  0.797449  0.404708  0.282289  0.457402  0.171406   
99997  0.440797  0.877096  0.807868  0.428558  0.277125  0.445573  0.165091   
99998  0.376476  0.698180  0.642255  0.292410  0.248230  0.551087  0.227597   
99999  0.414902  0.831954  0.772261  0.408535  0.302933  0.477249  0.186175   

              7         8  
0      0.165809  0.643375  
1      0.218292  0.629622  
2      0.202948  0.591164  
3      0.261619  0.624981  
4      0.273733  0.607946  
...         ...       ...  
99995  0.177232  0.647083  
99996  0.180510  0.637851  
99997  0.178455  0.642563  
99998  0.279015  0.545417  
99999  0.191660  0.616115  

[100000 rows x 9 columns]

In [55]:
td_id.columns = ['id']
td_id = pd.DataFrame(td_id)
td_id = td_id.to_numpy()
pred_df.insert(0,'id',td_id,True)
pred_df

id         0         1         2         3         4         5  \
0      200000  0.433285  0.883360  0.811159  0.430421  0.271398  0.451474   
1      200001  0.420300  0.828810  0.763612  0.408030  0.281587  0.455837   
2      200002  0.412057  0.793726  0.726100  0.388098  0.271827  0.513417   
3      200003  0.393646  0.780399  0.730757  0.477275  0.275011  0.456435   
4      200004  0.364035  0.759382  0.703418  0.363746  0.280633  0.483628   
...       ...       ...       ...       ...       ...       ...       ...   
99995  299995  0.447637  0.881927  0.812955  0.439417  0.280653  0.440188   
99996  299996  0.428932  0.863024  0.797449  0.404708  0.282289  0.457402   
99997  299997  0.440797  0.877096  0.807868  0.428558  0.277125  0.445573   
99998  299998  0.376476  0.698180  0.642255  0.292410  0.248230  0.551087   
99999  299999  0.414902  0.831954  0.772261  0.408535  0.302933  0.477249   

              6         7         8  
0      0.161206  0.165809  0.643375  
1      0.207079  0.218292  0.629622  
2      0.185814  0.202948  0.591164  
3      0.241996  0.261619  0.624981  
4      0.224548  0.273733  0.607946  
...         ...       ...       ...  
99995  0.162687  0.177232  0.647083  
99996  0.171406  0.180510  0.637851  
99997  0.165091  0.178455  0.642563  
99998  0.227597  0.279015  0.545417  
99999  0.186175  0.191660  0.616115  

[100000 rows x 10 columns]

In [57]:
pred_df.to_csv("KaggleSubmission_2.csv")